In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.chdir('C:\\Users\\Julian\\Desktop\\Cursos\\sets\\buses')
os.listdir()

df = pd.read_excel('VARIABLES LIMPIAS.xlsx')
df.head(2)

,ID,Model,Años,Tipologia,Capacidad,Marca,CILINDRAJE,Combustible,Fecha de Varada,Hora Varada,...,Fecha de revisión,Descripción de la revisión,Revisor,Fecha de habilitación,Habilitador,Zona,Ruta,Concatenar,Revisión,Tiempo habilitación
0,934,2021,4,BUS,80,VOLVO,7146.0,DIESEL,2024-01-01,05:55:52,...,2024-01-01 05:56:09,Móvil 407185/ O.T. 587154/ SE REALIZA CAMBIO ...,FLOTA-Isabel Cristina Ramirez Sanchez,2024-01-02 03:43:33,FLOTA-Isabel Cristina Ramirez Sanchez,Calle 80,669,Calle 80669,En Operación,21.794722
1,6339,2015,10,BUS,50,CHEVROLET,4570.0,DIESEL,2024-01-01,05:56:37,...,2024-01-01 05:56:52,Móvil 104397/ O.T. 751216/ REVISIÓN DE MÓVIL ...,FLOTA- MARCELA HERRERA,2024-01-01 09:57:43,FLOTA- MARCELA HERRERA,Usaquen,BK904,UsaquenBK904,En Operación,4.018333

In [3]:
df.shape, df.columns

((116215, 24),
 Index(['ID', 'Model', 'Años', 'Tipologia', 'Capacidad', 'Marca', 'CILINDRAJE',
        'Combustible', 'Fecha de Varada', 'Hora Varada', 'Franja',
        'Causa de la inmovilización', 'Descripción de la novedad', 'Creador',
        'Fecha de revisión', 'Descripción de la revisión', 'Revisor',
        'Fecha de habilitación', 'Habilitador', 'Zona', 'Ruta', 'Concatenar',
        'Revisión', 'Tiempo habilitación'],
       dtype='object'))

In [ ]:
df['Causa de la inmovilización'].unique()

array(['CARROCERÍA EXTERNA', 'ACELERACIÓN - POTENC', 'VANDALISMO',
       'SUSPENSIÓN', 'COMPRESOR', 'PUERTAS', 'SILLAS - PASAMANOS',
       'SE APAGA Y NO ENCIEN', 'FUGA DE AIRE', 'EMBRAGUE', 'CORREAS',
       'CAJA - TRANSMISIÓN', 'ACCIDENTE DE TRÁNSIT', 'FRENOS',
       'SISTEMA ELÉCTRICO', 'TESTIGOS-TABL INSTRU', 'RUTERO - INFORMADOR',
       'TEMPERATURA', 'DIRECCIÓN', 'COMBUSTIBLE', 'CARROCERÍA INTERNA',
       'FUGA DE ACEITE', 'FUGA DE REFRIGERANTE', 'RODAMIENTO LLANTA',
       'SEGURIDAD', 'MOTOR', 'TURBO', 'ACCESIBILIDAD DISCAP', 'CARDAN',
       'PERNO FIJACIÓN LLANT', 'AMBIENTAL', 'DOCUMENTOS', 'TROQUE ',
       'SISTEMA NEUMÁTICO', 'LIMPIAPARABRISAS', 'INMOV POR TRANSITO',
       'LLANTA SUELTA', 'SISTEMA ELÉCTRICO ', 'PUERTAS ',
       'CARROCERÍA EXTERNA ', 'DIRECCIÓN ', 'FUGA DE ACEITE ',
       'COMBUSTIBLE ', 'LLANTA LISA', 'SIRCI CONTROL',
       'CAJA - TRANSMISIÓN ', 'LIMPIAPARABRISAS ', 'MOTOR ',
       'CARROCERÍA INTERNA ', 'ZZZZZZZZZZ-O. CAU', 'ESTRUC - CHASIS ',
       'CORREAS ', 'ESTRUC - CHASIS', 'FRENOS ', 'LLANTA LISA ',
       'AMBIENTAL ', 'EMBRAGUE ', 'FUGA DE REFRIGERANTE ', 'TEMPERATURA ',
       'PERNO FIJACIÓN LLANT ', 'SILLAS - PASAMANOS ', 'FUGA DE AIRE ',
       'puertas', 'diRECCIÓN', 'SEGURIDAD ', 'motor',
       'SISTEMA NEUMÁTICO ', 'Z-DIRECCIÓN', 'RODAMIENTO LLANTA ',
       'TROQUE', 'RESTRICCIÓN POR INOPERATIVIDAD PROLONGADA', ' FRENOS',
       'ACCESIBILIDAD DISCAP ', 'SE APAGA Y NO ENCIEN ', 'SUSPENSIÓN ',
       'TURBO ', 'TESTIGOS-TABL INSTRU ', 'ACELERACIÓN - POTENC ',
       'SIRCI CONTROL ', 'MANGUERAS', 'PUERTAS  ', 'Z - OTRAS CAUSAS',
       'COMPRESOR ', 'PATIO', 'ACELERACIÓN - POTENCIA',
       'DIRECCIDIRECCIÓN'], dtype=object)

In [4]:
# Definamos nuestro vector de salida y

causas_explicables = ['TRANSMISIÓN', 'CAJA', 'EMBRAGUE', 'CARDAN','DIRECCIÓN', 'DIRECCIDIRECCIÓN', 'Z-DIRECCIÓN','diRECCIÓN','MOTOR', 'SE APAGA Y NO ENCIEN', 'TURBO', 'CORREAS','motor','FRENOS','FUGA DE ACEITE',
  'FUGA DE AIRE', 'FUGA DE REFRIGERANTE','SISTEMA ELÉCTRICO', 'TESTIGOS', 'TABL INSTRU', 'SIRCI CONTROL','ACELERACIÓN', 'POTENCIA']

df['Causa de la inmovilización'] = df['Causa de la inmovilización'].str.strip().str.upper()
y = df['Causa de la inmovilización'].isin(causas_explicables).astype(int)

In [16]:
df['y'] = y
df.head(3)

,ID,Model,Años,Tipologia,Capacidad,Marca,CILINDRAJE,Combustible,Fecha de Varada,Hora Varada,...,Descripción de la revisión,Revisor,Fecha de habilitación,Habilitador,Zona,Ruta,Concatenar,Revisión,Tiempo habilitación,y
0,934,2021,4,BUS,80,VOLVO,7146.0,DIESEL,2024-01-01,05:55:52,...,Móvil 407185/ O.T. 587154/ SE REALIZA CAMBIO ...,FLOTA-Isabel Cristina Ramirez Sanchez,2024-01-02 03:43:33,FLOTA-Isabel Cristina Ramirez Sanchez,Calle 80,669,Calle 80669,En Operación,21.794722,0
1,6339,2015,10,BUS,50,CHEVROLET,4570.0,DIESEL,2024-01-01,05:56:37,...,Móvil 104397/ O.T. 751216/ REVISIÓN DE MÓVIL ...,FLOTA- MARCELA HERRERA,2024-01-01 09:57:43,FLOTA- MARCELA HERRERA,Usaquen,BK904,UsaquenBK904,En Operación,4.018333,0
2,4880,2014,11,BUS,50,MERCEDES BENZ,4249.0,DIESEL,2024-01-01,05:57:15,...,"""Móvil 154151/ O.T. 751230/ \nSE REALIZA CAM...",FLOTA- MARCELA HERRERA,2024-01-01 08:29:15,FLOTA- MARCELA HERRERA,San Cristobal,LG816,San CristobalLG816,En Operación,2.533333,0

In [17]:
# Dummie

df['y'].value_counts()

y
0    75622
1    40593
Name: count, dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116215 entries, 0 to 116214
Data columns (total 25 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   ID                          116215 non-null  int64
 1   Model                       116215 non-null  int64
 2   Años                        116215 non-null  int64
 3   Tipologia                   116215 non-null  object
 4   Capacidad                   116215 non-null  int64
 5   Marca                       116215 non-null  object
 6   CILINDRAJE                  109455 non-null  float64
 7   Combustible                 116215 non-null  object
 8   Fecha de Varada             116215 non-null  datetime64[ns]
 9   Hora Varada                 80438 non-null   object
 10  Franja                      80438 non-null   object
 11  Causa de la inmovilización  116215 non-null  object
 12  Descripción de la novedad   116215 non-null  object
 13  Creador                     116215 non-null  object
 14  Fecha de revisión           116210 non-null  datetime64[ns]
 15  Descripción de la revisión  114864 non-null  object
 16  Revisor                     116210 non-null  object
 17  Fecha de habilitación       110270 non-null  datetime64[ns]
 18  Habilitador                 109951 non-null  object
 19  Zona                        116215 non-null  object
 20  Ruta                        116215 non-null  object
 21  Concatenar                  116215 non-null  object
 22  Revisión                    116215 non-null  object
 23  Tiempo habilitación         116215 non-null  float64
 24  y                           116215 non-null  int32
dtypes: datetime64[ns](3), float64(2), int32(1), int64(4), object(15)
memory usage: 21.7+ MB

In [26]:
df[['ID','y']].groupby('ID').sum()

      y
ID
185   3
186   5
187   4
188   3
189   4
...  ..
7774  4
7775  6
7776  8
7777  3
7778  9

[7594 rows x 1 columns]

In [27]:
# Definamos nuestra matriz de caracteristicas X

variables_X = ['Model','Años','Tipologia','Capacidad','Marca','CILINDRAJE','Combustible','Franja', 'Zona']


# Selección de variables
X = df[variables_X].copy()

X.head()

,Model,Años,Tipologia,Capacidad,Marca,CILINDRAJE,Combustible,Franja,Zona
0,2021,4,BUS,80,VOLVO,7146.0,DIESEL,a. m.,Calle 80
1,2015,10,BUS,50,CHEVROLET,4570.0,DIESEL,a. m.,Usaquen
2,2014,11,BUS,50,MERCEDES BENZ,4249.0,DIESEL,a. m.,San Cristobal
3,2021,4,BUS,80,SCANIA,9290.0,GNV,a. m.,Ciudad Bolivar
4,2020,5,BUS,80,SCANIA,9290.0,GNV,a. m.,Kennedy

In [28]:
# Codificación de variables

X.Franja.value_counts()

Franja
p. m.    45534
a. m.    34904
Name: count, dtype: int64

In [29]:
X = pd.get_dummies(X, columns=['Franja'], prefix='Franja', drop_first=True)
X.head()

,Model,Años,Tipologia,Capacidad,Marca,CILINDRAJE,Combustible,Zona,Franja_p. m.
0,2021,4,BUS,80,VOLVO,7146.0,DIESEL,Calle 80,False
1,2015,10,BUS,50,CHEVROLET,4570.0,DIESEL,Usaquen,False
2,2014,11,BUS,50,MERCEDES BENZ,4249.0,DIESEL,San Cristobal,False
3,2021,4,BUS,80,SCANIA,9290.0,GNV,Ciudad Bolivar,False
4,2020,5,BUS,80,SCANIA,9290.0,GNV,Kennedy,False

In [30]:
X = pd.get_dummies(X, columns= ['Tipologia'], prefix= 'Tipologia', drop_first= True)
X.head(3)

,Model,Años,Capacidad,Marca,CILINDRAJE,Combustible,Zona,Franja_p. m.,Tipologia_BUS
0,2021,4,80,VOLVO,7146.0,DIESEL,Calle 80,False,True
1,2015,10,50,CHEVROLET,4570.0,DIESEL,Usaquen,False,True
2,2014,11,50,MERCEDES BENZ,4249.0,DIESEL,San Cristobal,False,True

In [31]:
X.Marca.nunique(), X.Combustible.nunique(), X.Zona.nunique()

(12, 5, 18)

In [32]:
print(X.Combustible.unique())

X['Combustible'] = X['Combustible'].replace({
    'ELÉCTRICO': 'ELECTRICO',
    'EL�CTRICO': 'ELECTRICO',
    'HIBRIDO (DIESEL - ELECTRICO)': 'HIBRIDO',
})

X['Combustible'].unique()

['DIESEL' 'GNV' 'ELECTRICO' 'HIBRIDO (DIESEL - ELECTRICO)' 'EL�CTRICO']

array(['DIESEL', 'GNV', 'ELECTRICO', 'HIBRIDO'], dtype=object)

In [33]:
X.Marca.unique()

array(['VOLVO', 'CHEVROLET', 'MERCEDES BENZ', 'SCANIA', 'BYD', 'HINO',
       'AGRALE', 'THOMAS BUILT', 'VOLKSWAGEN', 'BLUEBIRD',
       'INTERNACIONAL', 'YUTONG'], dtype=object)

In [34]:
X.Zona.unique()

array(['Calle 80', 'Usaquen', 'San Cristobal', 'Ciudad Bolivar',
       'Kennedy', 'Engativa', 'Fontibon IV', 'Perdomo II', 'Usme III',
       'Bosa', 'Usme II', 'Suba Centro III', 'Suba Oriental',
       'Tintal - Zona Franca', 'Fontibon V', 'Fontibon III',
       'Fontibon II', 'Suba Centro VI'], dtype=object)

In [35]:
# Aplicamos one-hot encoding 

X = pd.get_dummies(X, columns=['Marca'], prefix='Marca', drop_first=True)
X.head(2)

,Model,Años,Capacidad,CILINDRAJE,Combustible,Zona,Franja_p. m.,Tipologia_BUS,Marca_BLUEBIRD,Marca_BYD,Marca_CHEVROLET,Marca_HINO,Marca_INTERNACIONAL,Marca_MERCEDES BENZ,Marca_SCANIA,Marca_THOMAS BUILT,Marca_VOLKSWAGEN,Marca_VOLVO,Marca_YUTONG
0,2021,4,80,7146.0,DIESEL,Calle 80,False,True,False,False,False,False,False,False,False,False,False,True,False
1,2015,10,50,4570.0,DIESEL,Usaquen,False,True,False,False,True,False,False,False,False,False,False,False,False

In [36]:
X = pd.get_dummies(X, columns=['Zona'], prefix='Zona', drop_first=True)
X.head(2)

,Model,Años,Capacidad,CILINDRAJE,Combustible,Franja_p. m.,Tipologia_BUS,Marca_BLUEBIRD,Marca_BYD,Marca_CHEVROLET,...,Zona_Kennedy,Zona_Perdomo II,Zona_San Cristobal,Zona_Suba Centro III,Zona_Suba Centro VI,Zona_Suba Oriental,Zona_Tintal - Zona Franca,Zona_Usaquen,Zona_Usme II,Zona_Usme III
0,2021,4,80,7146.0,DIESEL,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2015,10,50,4570.0,DIESEL,False,True,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [37]:
X = pd.get_dummies(X, columns=['Combustible'], prefix='Combustible', drop_first=True)
X.head(2)

,Model,Años,Capacidad,CILINDRAJE,Franja_p. m.,Tipologia_BUS,Marca_BLUEBIRD,Marca_BYD,Marca_CHEVROLET,Marca_HINO,...,Zona_Suba Centro III,Zona_Suba Centro VI,Zona_Suba Oriental,Zona_Tintal - Zona Franca,Zona_Usaquen,Zona_Usme II,Zona_Usme III,Combustible_ELECTRICO,Combustible_GNV,Combustible_HIBRIDO
0,2021,4,80,7146.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2015,10,50,4570.0,False,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False

In [38]:
X.drop('Model', axis=1, inplace= True)
X.head(2)

,Años,Capacidad,CILINDRAJE,Franja_p. m.,Tipologia_BUS,Marca_BLUEBIRD,Marca_BYD,Marca_CHEVROLET,Marca_HINO,Marca_INTERNACIONAL,...,Zona_Suba Centro III,Zona_Suba Centro VI,Zona_Suba Oriental,Zona_Tintal - Zona Franca,Zona_Usaquen,Zona_Usme II,Zona_Usme III,Combustible_ELECTRICO,Combustible_GNV,Combustible_HIBRIDO
0,4,80,7146.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,10,50,4570.0,False,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False

In [39]:
X.isna().sum()

Años                            0
Capacidad                       0
CILINDRAJE                   6760
Franja_p. m.                    0
Tipologia_BUS                   0
Marca_BLUEBIRD                  0
Marca_BYD                       0
Marca_CHEVROLET                 0
Marca_HINO                      0
Marca_INTERNACIONAL             0
Marca_MERCEDES BENZ             0
Marca_SCANIA                    0
Marca_THOMAS BUILT              0
Marca_VOLKSWAGEN                0
Marca_VOLVO                     0
Marca_YUTONG                    0
Zona_Calle 80                   0
Zona_Ciudad Bolivar             0
Zona_Engativa                   0
Zona_Fontibon II                0
Zona_Fontibon III               0
Zona_Fontibon IV                0
Zona_Fontibon V                 0
Zona_Kennedy                    0
Zona_Perdomo II                 0
Zona_San Cristobal              0
Zona_Suba Centro III            0
Zona_Suba Centro VI             0
Zona_Suba Oriental              0
Zona_Tintal - Zona Franca       0
Zona_Usaquen                    0
Zona_Usme II                    0
Zona_Usme III                   0
Combustible_ELECTRICO           0
Combustible_GNV                 0
Combustible_HIBRIDO             0
dtype: int64

In [40]:
X.shape, y.shape

((116215, 36), (116215,))

In [41]:
# Crear máscara booleana para filas sin NaN en X
mask = ~X.isna().any(axis=1)

# Filtrar X e y usando esa máscara para mantener filas iguales
X = X[mask]
y = y[mask]

In [42]:
X.shape, y.shape

((109455, 36), (109455,))

# Regresión logistica

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Separar en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Escalado (no siempre necesario, pero mejora estabilidad numérica)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Entrenar modelo
logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [44]:
# Predicción
y_pred = logreg.predict(X_test_scaled)

# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Accuracy: 0.6401260792106345

Matriz de confusión:
 [[13866   142]
 [ 7736   147]]

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.64      0.99      0.78     14008
           1       0.51      0.02      0.04      7883

    accuracy                           0.64     21891
   macro avg       0.58      0.50      0.41     21891
weighted avg       0.59      0.64      0.51     21891

## Arboles de decisión

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = clf.predict(X_test)

# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Accuracy: 0.6397149513498698

Matriz de confusión:
 [[13747   261]
 [ 7626   257]]

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.64      0.98      0.78     14008
           1       0.50      0.03      0.06      7883

    accuracy                           0.64     21891
   macro avg       0.57      0.51      0.42     21891
weighted avg       0.59      0.64      0.52     21891

## Reducción de dimensionalidad PCA

In [47]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=0.95)  # 95% de la varianza
X_pca = pca.fit_transform(X_scaled)

X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# Regresión logística

logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train_scaled, y_train)

y_pred = logreg.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Accuracy: 0.6401260792106345

Matriz de confusión:
 [[13866   142]
 [ 7736   147]]

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.64      0.99      0.78     14008
           1       0.51      0.02      0.04      7883

    accuracy                           0.64     21891
   macro avg       0.58      0.50      0.41     21891
weighted avg       0.59      0.64      0.51     21891

In [49]:
# Arboles

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Accuracy: 0.6397149513498698

Matriz de confusión:
 [[13748   260]
 [ 7627   256]]

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.64      0.98      0.78     14008
           1       0.50      0.03      0.06      7883

    accuracy                           0.64     21891
   macro avg       0.57      0.51      0.42     21891
weighted avg       0.59      0.64      0.52     21891

## Prueba con datos balanceados

In [50]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

C:\Users\Julian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(

In [53]:
y_res.value_counts()

Causa de la inmovilización
0    70039
1    70039
Name: count, dtype: int64

In [55]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_res)

pca = PCA(n_components=0.95)  # 95% de la varianza
X_pca = pca.fit_transform(X_scaled)

X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y_res, test_size=0.2, random_state=42, stratify=y_res)

In [56]:
# Arboles

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Accuracy: 0.5702812678469446

Matriz de confusión:
 [[6768 7240]
 [4799 9209]]

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.59      0.48      0.53     14008
           1       0.56      0.66      0.60     14008

    accuracy                           0.57     28016
   macro avg       0.57      0.57      0.57     28016
weighted avg       0.57      0.57      0.57     28016